### ISSUE TITLE
Unreproducable issue: reduntant chat messages

### ISSUE THREAD

**Issue by Dansoftowner** [Dansoftowner/14AB-A-plander-frontend#117]
I wrote some messages then exited the browser. However, when I opened it up again: my messages were duplicated:

![Screenshot_2024-02-21-16-50-56-741_com.android.chrome.jpg](https://github.com/Dansoftowner/14AB-A-plander-frontend/assets/49782833/46bfa06e-7fba-4291-bfac-353d66c01e25)

It's hard to identify the exact problem, but it should be under investigation.

**Comment by feherszabolcs** [comment]
I was able to reproduce this type of issue somehow. Actually it is fixed automatically, I was just looking it and the duplicate message disappeared. I keep the issue open for any further information.
