### ISSUE TITLE
Unable to change report method and type

### ISSUE THREAD

**Issue by KubikArmin** [Dansoftowner/14AB-A-plander-frontend#120]
When editing a report, the method and type fields values should be deleted
Before:
![image](https://github.com/Dansoftowner/14AB-A-plander-frontend/assets/62424812/cea06656-baab-46c7-bd9a-88ef176050ee)
After:
![image](https://github.com/Dansoftowner/14AB-A-plander-frontend/assets/62424812/600a9a24-410d-4990-9938-55b32999025e)

**Comment by feherszabolcs** [comment]
Asked to modify the backend to solve this problem.
