### ISSUE TITLE
Delete button should be different for the current member in the member list

### ISSUE THREAD

**Issue by Dansoftowner** [Dansoftowner/14AB-A-plander-frontend#37]
In the members page, if a member card represents the member who is currently logged in,  the '🗑️' should be an 'exit association' icon. 

For example:
 ![logout icon](https://static-00.iconduck.com/assets.00/logout-icon-512x512-l2vcoia9.png)

**Comment by feherszabolcs** [comment]
The member can only leave the association if the president kick him out. The president has to know if someone leave.
