### ISSUE TITLE
Reports' page

### ISSUE THREAD

**Issue by Dansoftowner** [Dansoftowner/14AB-A-plander-frontend#73]
- Posesses it's own menu item 
- Simularly to the assignments' page, it should have a calendar
- The only major difference here is that when the user clicks an assignment, a slightly different alert dialog comes up for adding/editing reports
- Only assignments from the past should be loaded 
- Assignments that already have reports should be marked with a green color, others should be indicated with yellow

**Comment by feherszabolcs** [comment]
- Reports only editable if the creation date is not older than 3 days
- implement patch for editable reports
