### ISSUE TITLE
The timestamp should be displayed for the chat messages

### ISSUE THREAD

**Issue by Dansoftowner** [Dansoftowner/14AB-A-plander-frontend#99]
Different formats for different scenarios:
- If the message was sent on the current day: `HH:mm`
- If the message was sent on the current week: `Day HH:mm`
- If the message was sent in the current year: `Month DD:HH:mm`
- Otherwise: `YYYY.MM.DD HH:mm`

**Comment by feherszabolcs** [comment]
Implemented, but no different fomat for the current week.
